name: notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  connectivity_plus: ^6.1.4
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  isar:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  lottie: ^3.3.1
  path_provider: ^2.1.5
  popover: ^0.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: 3.1.8

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/lottie/

  fonts:
    - family: DmSerifText
      fonts:
        - asset: assets/fonts/DMSerifText-Regular.ttf